//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: ComVisible(false)]
[assembly: Guid("D06291D7-7B5E-4A5C-8C73-3F79DCF98F41")]
[assembly: AssemblyCompany("Primetec GmbH")]
[assembly: AssemblyCopyright("© 2023 Primetec GmbH")]
[assembly: AssemblyProduct("Primetec.Sample.NuGet1")]
[assembly: AssemblyTitle("Test NuGet deploy & publish")]
[assembly: AssemblyDescription("Test NuGet deploy & publish")]
[assembly: AssemblyVersion("0.0.3.0")]
[assembly: AssemblyFileVersion("0.0.3.0")]

// Von der MSBuild WriteCodeFragment-Klasse generiert.

